### ISSUE TITLE
📌 Issue: Implementing Jekyll for GitHub Pages

### ISSUE THREAD

**Issue by IntensiveAlpha** [Frank-Dex-Devs/Jar-Var-Script#17]
**Description:**
We need to implement Jekyll for our GitHub Pages website to enhance its functionality, customization, and maintainability. Jekyll is a static site generator that will enable us to streamline the development process and automate certain tasks.

**Tasks:**
1. **Setup Jekyll Environment:** Install and set up Jekyll on our local development environment. This involves installing the necessary dependencies and ensuring compatibility with our existing project structure.

2. **Integrate Jekyll with GitHub Pages:** Configure our GitHub repository to recognize Jekyll as the static site generator for our GitHub Pages website. Ensure that the appropriate settings are enabled in the repository settings.

3. **Create Basic Jekyll Site:** Initialize a basic Jekyll site within our project structure. This will serve as the foundation for our website and allow us to start customizing its layout and content.

4. **Implement Theme Selection:** Research and select a Jekyll theme that aligns with our branding and design requirements. Integrate the chosen theme into our Jekyll site and customize it to suit our needs.

5. **Configure Navigation and Layout:** Set up navigation menus, header, footer, and other layout elements to ensure a consistent and intuitive user experience across the site. Customize the layout as needed to accommodate our content structure.

6. **Migrate Content:** Migrate existing content from our current website to the new Jekyll site. This includes pages, blog posts, images, and any other relevant assets. Ensure that all URLs are properly redirected to maintain SEO and user accessibility.

7. **Optimize SEO and Metadata:** Enhance the Jekyll site's SEO by implementing appropriate meta tags, structured data, and optimizing page titles, descriptions, and URLs. This will improve search engine visibility and ensure a better user experience when sharing our content on social media platforms.

8. **Testing and Deployment:** Thoroughly test the Jekyll implementation, ensuring that all links, assets, and functionalities work correctly. Deploy the Jekyll site to GitHub Pages and verify its functionality and responsiveness on different devices and browsers.

**Estimated Time:** This implementation is expected to take approximately 2-3 weeks, considering the complexity of the existing website and the customization requirements.

**Additional Notes:** Please ensure that all necessary documentation and instructions are provided to guide future maintenance and updates of the Jekyll implementation.

Let's embrace the power of Jekyll to enhance our GitHub Pages website and provide a more efficient and customizable experience for our users!

Regards,
@IntensiveAlpha  🦁

**Comment by IntensiveAlpha** [comment]
💛 This is an incredible idea. Let's work. 👍

**Comment by LUCASFRANKINC** [comment]
Hi team,

I opted to move the docs to frank-dex-devs.github.io and separate the docs from  the tutorial. Please check if it works 🤞🏽 .

**Comment by LUCASFRANKINC** [comment]
I will close this now.
